# This file should contain all the record creation needed to seed the database with its default values.")
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).")
#")
# Examples:")
#")
#   movies = Movie.create([{ name: 'Star Wars' }",                      "{ name: 'Lord of the Rings' }])")
#   Character.create(name: 'Luke'",                      "movie: movies.first)")

City.create(name: "카라치",          population: "24600000", definition: "도시구역",                    area: "3527",       density: "6975",    country: "파키스탄",              continent: "아시아")
City.create(name: "상하이",          population: "24230000", definition: "중심지구",                    area: "2605.8",     density: "9301",    country: "중국",                  continent: "아시아")
City.create(name: "델리",            population: "16349831", definition: "시자치단체",                  area: "1397.29",    density: "11320",   country:  "인도",                 continent: "아시아")
City.create(name: "라고스",          population: "16060303", definition: "Statistical area",            area: "999.6",      density: "16077",   country:  "나이지리아",           continent: "아프리카")
City.create(name: "이스탄불",        population: "13710512", definition: "광역지방자치단체",            area: "5343",       density: "2567",    country: "터키",                  continent: "유럽/아시아")
City.create(name: "도쿄",            population: "13297629", definition: "도쿄 도 구부",                area: "2198",       density: "6075",    country: "일본",                  continent: "아시아")
City.create(name: "뭄바이",          population: "12478447", definition: "시자치단체",                  area: "603",        density: "20694",   country:  "인도",                 continent: "아시아")
City.create(name: "모스크바",        population: "11977988", definition: "연방시",                      area: "2511",       density: "4705",    country: "러시아",                continent: "유럽")
City.create(name: "상파울루",        population: "11821876", definition: "자치제",                      area: "1523",       density: "7762",    country: "브라질",                continent: "남아메리카")
City.create(name: "베이징",          population: "11716000", definition: "중심지구",                    area: "1368.32",    density: "7400",    country: "중국",                  continent: "아시아")
City.create(name: "톈진",            population: "11090314", definition: "모든 지구",                   area: "7422",       density: "1494",    country: "중국",                  continent: "아시아")
City.create(name: "킨샤사",          population: "11250000", definition: "도시-주",                     area: "1117",       density: "10071",   country:  "콩고 민주 공화국",     continent: "아프리카")
City.create(name: "광저우",          population: "11070654", definition: "모든 지구",                   area: "3843",       density: "2881",    country: "중국",                  continent: "아시아")
City.create(name: "선전",            population: "10357938", definition: "모든 지구",                   area: "1989",       density: "5201",    country: "중국",                  continent: "아시아")
City.create(name: "카이로",          population: "10230350", definition: "Governorate",                 area: "528",        density: "19375",   country:  "이집트",               continent: "아프리카")
City.create(name: "자카르타",        population: "10187595", definition: "특별수도권",                  area: "662.33",     density: "15400",   country:  "인도네시아",           continent: "아시아")
City.create(name: "라호르",          population: "10052000", definition: "City District",               area: "1772",       density: "5968",    country: "파키스탄",              continent: "아시아")
City.create(name: "서울",            population: "9995784",  definition: "특별시",                      area: "605.25",     density: "16521",   country:  "대한민국",             continent: "아시아")
City.create(name: "멕시코시티",      population: "8873017",  definition: "연방시",                      area: "1485.49",    density: "5973",    country: "멕시코",                continent: "중앙아메리카")
City.create(name: "방갈로르",        population: "8425970",  definition: "시자치단체",                  area: "709.5",      density: "11876",   country:  "인도",                 continent: "아시아")
City.create(name: "뉴욕",            population: "8336697",  definition: "City proper",                 area: "783.7",      density: "10637",   country:  "미국",                 continent: "북아메리카")
City.create(name: "런던",            population: "8308369",  definition: "그레이터 런던",               area: "1572",       density: "5285",    country: "영국",                  continent: "유럽")
City.create(name: "방콕",            population: "8280925",  definition: "행정구역",                    area: "1568.74",    density: "5280",    country: "타이",                  continent: "아시아")
City.create(name: "테헤란",          population: "8244535",  definition: "City proper",                 area: "760",        density: "10359",   country:  "이란",                 continent: "아시아")
City.create(name: "둥관 시",         population: "8220237",  definition: "Prefecture-level city",       area: "2465",       density: "3335",    country: "중국",                  continent: "아시아")
City.create(name: "다카",            population: "7906000",  definition: "시자치단체",                  area: "360",        density: "26353",   country:  "방글라데시",           continent: "아시아")
City.create(name: "리마",            population: "7605742",  definition: "Province",                    area: "2670.4",     density: "2848",    country: "페루",                  continent: "남아메리카")
City.create(name: "호치민 시티",     population: "7521138",  definition: "Province-level municipality", area: "2095.01",    density: "3590",    country: "베트남",                continent: "아시아")
City.create(name: "보고타",          population: "7467804",  definition: "수도권",                      area: "1590",       density: "4697",    country: "콜롬비아",              continent: "남아메리카")
City.create(name: "홍콩",            population: "7108100",  definition: "특별행정구",                  area: "1108",       density: "6415",    country: "HK",                    continent: "아시아")
City.create(name: "하이데라바드",    population: "6809970",  definition: "시자치단체",                  area: "621.48",     density: "10958",   country:  "인도",                 continent: "아시아")
City.create(name: "하노이",          population: "6451909",  definition: "Province-level municipality", area: "3344.7",     density: "1943.4",  country:   "베트남",              continent: "아시아")
City.create(name: "우한 시",         population: "6434373",  definition: "Central districts",           area: "888.42",     density: "7242",    country: "중국",                  continent: "아시아")
City.create(name: "리우데자네이루",  population: "6390290",  definition: "지방 자치제",                 area: "1182",       density: "5406",    country: "브라질",                continent: "남아메리카")
City.create(name: "아마다바드",      population: "5570585",  definition: "시자치단체",                  area: "475",        density: "11727",   country:  "인도",                 continent: "아시아")
City.create(name: "바그다드",        population: "5402486",  definition: "City proper",                 area: "1134",       density: "4064",    country: "이라크",                continent: "아시아")
City.create(name: "리야드",          population: "5188286",  definition: "City proper",                 area: "800",        density: "6485",    country: "사우디아라비아",        continent: "아시아")
City.create(name: "싱가포르",        population: "5183700",  definition: "도시 국가",                   area: "712.4",      density: "7276",    country: "싱가포르",              continent: "아시아")
City.create(name: "제다",            population: "5112018",  definition: "City proper",                 area: "1230",       density: "2789",    country: "사우디아라비아",        continent: "아시아")
City.create(name: "상트페테르부르크",population: "5023313",  definition: "연방시",                      area: "1399",       density: "3480",    country: "러시아",                continent: "유럽")
City.create(name: "산티아고",        population: "5012973",  definition: "Province",                    area: "2030",       density: "2469",    country: "칠레",                  continent: "남아메리카")
City.create(name: "첸나이",          population: "4681087",  definition: "시자치단체",                  area: "176",        density: "26903",   country:  "인도",                 continent: "아시아")
City.create(name: "앙카라",          population: "4550662",  definition: "광역지방자치단체",            area: "2516",       density: "1551",    country: "터키",                  continent: "아시아")
City.create(name: "충칭",            population: "4513100",  definition: "Core districts",              area: "1435",       density: "3145",    country: "중국",                  continent: "아시아")
City.create(name: "콜카타",          population: "4486679",  definition: "시자치단체",                  area: "185",        density: "24252",   country:  "인도",                 continent: "아시아")
City.create(name: "수라트",          population: "4462002",  definition: "시자치단체",                  area: "326.515",    density: "13666",   country:  "인도",                 continent: "아시아")
City.create(name: "양곤",            population: "4350000",  definition: "City proper",                 area: "598.75",     density: "6828",    country: "미얀마",                continent: "아시아")
City.create(name: "알렉산드리아",    population: "4110015",  definition: "Governorate",                 area: "2680",       density: "1611",    country: "이집트",                continent: "아프리카")
City.create(name: "선양",            population: "4101197",  definition: "Core districts",              area: "3495",       density: "1173",    country: "중국",                  continent: "아시아")
City.create(name: "쑤저우",          population: "4074000",  definition: "Core districts",              area: "1679.2",     density: "2426",    country: "중국",                  continent: "아시아")
City.create(name: "신베이시",        population: "3910086",  definition: "Special municipality",        area: "2052.5667",  density: "1905",    country: "중화민국",              continent: "아시아")
City.create(name: "요하네스버그",    population: "3888180",  definition: "Metropolitan Municipality",   area: "1644.96",    density: "2364",    country: "남아프리카 공화국",     continent: "아프리카")
City.create(name: "로스앤젤레스",    population: "3819702",  definition: "City proper",                 area: "1290",       density: "2940",    country: "미국",                  continent: "북아메리카")
City.create(name: "요코하마",        population: "3680267",  definition: "City proper",                 area: "437.38",     density: "8414",    country: "일본",                  continent: "아시아")
City.create(name: "아비장",          population: "3660682",  definition: "Department/District",         area: "2119",       density: "1728",    country: "코트디부아르",          continent: "아프리카")
City.create(name: "부산",            population: "3600381",  definition: "광역시",                      area: "766.12",     density: "4666",    country: "대한민국",              continent: "아시아")
City.create(name: "베를린",          population: "3499879",  definition: "City state",                  area: "892",        density: "3924",    country: "독일",                  continent: "유럽")
City.create(name: "케이프타운",      population: "3497097",  definition: "Metropolitan Municipality",   area: "2454.72",    density: "1424",    country: "남아프리카 공화국",     continent: "아프리카")
City.create(name: "더반",            population: "3468086",  definition: "Metropolitan Municipality",   area: "2291.89",    density: "1513",    country: "남아프리카 공화국",     continent: "아프리카")
City.create(name: "카사블랑카",      population: "3427000",  definition: "City proper",                 area: "386",        density: "8878",    country: "모로코",                continent: "아프리카")
City.create(name: "평양",            population: "3255388",  definition: "직할시",                      area: "3194",       density: "1019",    country: "조선민주주의인민공화국",continent: "아시아")
City.create(name: "마드리드",        population: "3213271",  definition: "자치시",                      area: "698",        density: "4604",    country: "스페인",                continent: "유럽")
City.create(name: "나이로비",        population: "3138369",  definition: "City-county",                 area: "696",        density: "4509",    country: "케냐",                  continent: "아프리카")
City.create(name: "푸네",            population: "3115431",  definition: "시자치단체",                  area: "450.69",     density: "6913",    country: "인도",                  continent: "아시아")
City.create(name: "자이푸르",        population: "3073350",  definition: "시자치단체",                  area: "485",        density: "6337",    country: "인도",                  continent: "아시아")
City.create(name: "아디스아바바",    population: "3040740",  definition: "City proper",                 area: "527",        density: "5165",    country: "에티오피아",            continent: "아프리카")
